In [1]:
import pandas as pd

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import OneHotEncoder

In [17]:
encodings = ["utf-8", "utf-8-sig", "latin-1", "cp1252"]

for enc in encodings:
    try:
        df = pd.read_csv("spam.csv", encoding=enc)
        print(enc, "works")
    except:
        print(enc, "does not work")

utf-8 does not work
utf-8-sig does not work
latin-1 works
cp1252 works

In [2]:
df = pd.read_csv("./spam.csv",encoding='latin-1')

df.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [3]:
df.shape
df.columns

Index(['v1', 'v2', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], dtype='object')

In [4]:
df = df[["v1", "v2"]]

df.head()

     v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [5]:
df.columns = ["label", "message"]

df.head()

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [6]:
df.isnull().sum()

label      0
message    0
dtype: int64

In [7]:
df["label"].value_counts()

label
ham     4825
spam     747
Name: count, dtype: int64

In [8]:
bow_vectorizer = CountVectorizer()

bow_matrix = bow_vectorizer.fit_transform(df["message"])

In [9]:
bow_matrix.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(5572, 8672))

In [10]:
bow_words = bow_vectorizer.get_feature_names_out()

print(bow_words[:50])

['00' '000' '000pes' '008704050406' '0089' '0121' '01223585236'
 '01223585334' '0125698789' '02' '0207' '02072069400' '02073162414'
 '02085076972' '021' '03' '04' '0430' '05' '050703' '0578' '06' '07'
 '07008009200' '07046744435' '07090201529' '07090298926' '07099833605'
 '07123456789' '0721072' '07732584351' '07734396839' '07742676969'
 '07753741225' '0776xxxxxxx' '07781482378' '07786200117' '077xxx' '078'
 '07801543489' '07808' '07808247860' '07808726822' '07815296484'
 '07821230901' '078498' '07880867867' '0789xxxxxxx' '07946746291'
 '0796xxxxxx']

In [11]:
first_bow = bow_matrix[0].toarray()[0]

word_positions = first_bow.nonzero()[0]

bow_result = pd.DataFrame({
    "Word": bow_words[word_positions],
    "Count": first_bow[word_positions]
})

bow_result

         Word  Count
0       amore      1
1   available      1
2      buffet      1
3       bugis      1
4        cine      1
5       crazy      1
6          go      1
7         got      1
8       great      1
9          in      1
10     jurong      1
11         la      1
12       only      1
13      point      1
14      there      1
15      until      1
16        wat      1
17      world      1

In [12]:
tfidf_vectorizer = TfidfVectorizer()

tfidf_matrix = tfidf_vectorizer.fit_transform(df["message"])
tfidf_matrix.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(5572, 8672))

In [13]:
tfidf_words = tfidf_vectorizer.get_feature_names_out()

print(tfidf_words[:50])

['00' '000' '000pes' '008704050406' '0089' '0121' '01223585236'
 '01223585334' '0125698789' '02' '0207' '02072069400' '02073162414'
 '02085076972' '021' '03' '04' '0430' '05' '050703' '0578' '06' '07'
 '07008009200' '07046744435' '07090201529' '07090298926' '07099833605'
 '07123456789' '0721072' '07732584351' '07734396839' '07742676969'
 '07753741225' '0776xxxxxxx' '07781482378' '07786200117' '077xxx' '078'
 '07801543489' '07808' '07808247860' '07808726822' '07815296484'
 '07821230901' '078498' '07880867867' '0789xxxxxxx' '07946746291'
 '0796xxxxxx']

In [14]:
first_tfidf = tfidf_matrix[0].toarray()[0]

word_positions = first_tfidf.nonzero()[0]

tfidf_result = pd.DataFrame({
    "Word": tfidf_words[word_positions],
    "TF-IDF": first_tfidf[word_positions]
})

tfidf_result

         Word    TF-IDF
0       amore  0.326425
1   available  0.244155
2      buffet  0.311608
3       bugis  0.275765
4        cine  0.275765
5       crazy  0.252794
6          go  0.148130
7         got  0.153189
8       great  0.180318
9          in  0.107204
10     jurong  0.326425
11         la  0.275765
12       only  0.156180
13      point  0.255315
14      there  0.155664
15      until  0.229985
16        wat  0.182387
17      world  0.220801

In [15]:
onehot_encoder = OneHotEncoder(sparse_output=False)

label_onehot = onehot_encoder.fit_transform(df[["label"]])

In [16]:
onehot_df = pd.DataFrame(
    label_onehot,
    columns=onehot_encoder.get_feature_names_out(["label"])
)

onehot_df.head()

   label_ham  label_spam
0        1.0         0.0
1        1.0         0.0
2        0.0         1.0
3        1.0         0.0
4        1.0         0.0